/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEvent: typeof import('./src/components/calandar/AddEvent.vue')['default']
    Calandar: typeof import('./src/components/calandar/Calandar.vue')['default']
    CreateGroup: typeof import('./src/components/calandar/CreateGroup.vue')['default']
    GroupManage: typeof import('./src/components/calandar/groupManage.vue')['default']
    GroupManagement: typeof import('./src/components/calandar/GroupManagement.vue')['default']
    GroupManagent: typeof import('./src/components/calandar/GroupManagent.vue')['default']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/signUp/SignUp.vue')['default']
    VisualizeEvent: typeof import('./src/components/calandar/VisualizeEvent.vue')['default']
  }
}
